export const ADD_CART="ADD_CART";
export const CHANGE_QTY="CHANGE_QTY";
export const REMOVE_PRODUCT="REMOVE_PRODUCT";
export const CHOOSE_SHIPPING="CHOOSE_SHIPPING";
export const ADD_PRODUCTS="ADD_PRODUCTS";
export const SAVE_ADDRESS="SAVE_ADDRESS";
export const SAVE_SIZE="SAVE_ADDRESS";
export const SAVE_PACKAGING="SAVE_PACKAGING";